### ISSUE TITLE
VNET Peerings query issues

### ISSUE THREAD

**Issue by Dfintz** [Azure/ccodashboard#37] opened 2019-07-09 14:26 UTC
On the V5.2 we encountered the below error. To bypass it we spitted the VNET Peerings query to tow, a staging  and transformation one.

VNET Peerings
OLE DB or ODBC error: Query 'Unique VNET Peerings' (step 'ListVNETPeerings') references other queries or steps, so it may not directly access a data source. Please rebuild this data combination.

**Comment by josunefon** [comment] 2019-07-09 20:38
Hi @Dfintz, to solve this problem you have to modify the privacy settings (File -> Options -> Privacy) to **Always ignore privacy level settings** and refresh again the report.

![image](https://user-images.githubusercontent.com/39730064/60920947-3e6d2580-a24e-11e9-9042-f799c9f6fc53.png)

The reason is the way how we're obtaining this data. It will be fixed in the next versions.

**Closed** 2019-07-09 22:26 UTC
Labels: bug

**Comment by eosho** [comment] 2020-02-19 16:54
@josunefon is this fixed ? I am running into issues with my customer getting this error. I am unable to reproduce it myself

**Comment by josunefon** [comment] 2020-02-19 17:08
Hi @eosho no, after trying different methods to obtain the data, there's no other way to create this view. Let's wait for the new version of the API to see if this problem is fixed and we can obtain all the data in one request.

The solution is still ignore the privacy levels
