### ISSUE TITLE
"IaaS Usage and limits" error

### ISSUE THREAD

**Issue by Yanunita** [Azure/ccodashboard#146] opened 2021-01-31 10:53 UTC
Hello, we can't update "IaaS Usage and limits". We have this error (picture) 

![image](https://user-images.githubusercontent.com/66009606/106381690-de534c80-63ba-11eb-834f-944978fe6b75.png)

Can you help us?

thanks.

**Comment by josunefon** [comment] 2021-02-12 09:45
Hi @Yanunita,

Power BI Desktop and the model must be in English.
![image](https://user-images.githubusercontent.com/39730064/107752653-56a50080-6d1f-11eb-87fb-4aabd03e832e.png)

**Comment by tksh164** [comment] 2021-02-18 08:13
The following is probably the same issue. It is in English environment. I use `CCO Power BI Infra Dashboard v8.2.pbit`

![image](https://user-images.githubusercontent.com/1618784/108325297-49e74780-720c-11eb-88d1-46ceca8f7a6e.png)

![image](https://user-images.githubusercontent.com/1618784/108325393-61becb80-720c-11eb-9a44-95ca741507d1.png)

**Comment by josunefon** [comment] 2021-02-25 15:19
Hi @tksh164 

Is this problem still happening?

**Comment by tksh164** [comment] 2021-02-26 08:27
Hi @josunefon, this issue still happened in my environment after my previous comment.

![image](https://user-images.githubusercontent.com/1618784/109272152-d40a5e00-7853-11eb-95d5-ae17e929b2c9.png)

![image](https://user-images.githubusercontent.com/1618784/109272168-d79de500-7853-11eb-8e40-f5c522e81f41.png)

But now, I tried to investigate this issue. I think the data type of 'ComputeNetStorageUsage'[currentValue] and 'ComputeNetStorageUsage'[limit] fields are the cause of this issue. These field's data type is **Text**, so cannot **SUM**.

I changed those field's data type to **Whole number** then, this issue resolved in my environment.

(Click to zoom)

![image](https://user-images.githubusercontent.com/1618784/109272895-d5885600-7854-11eb-8731-937d7023b0c0.png)

![image](https://user-images.githubusercontent.com/1618784/109273269-4fb8da80-7855-11eb-88e9-cff6ac93fa0d.png)

![image](https://user-images.githubusercontent.com/1618784/109273651-d2419a00-7855-11eb-8b1e-61b1f77fff36.png)

![image](https://user-images.githubusercontent.com/1618784/109274963-6fe99900-7857-11eb-80d9-b821b7ac1cba.png)

![image](https://user-images.githubusercontent.com/1618784/109275004-7e37b500-7857-11eb-9b27-d79158f0b4b7.png)

**Comment by josunefon** [comment] 2021-03-08 11:21
Thanks @takashih87, we'll fix this in the next release

**Closed by josunefon** 2021-03-08 11:21 UTC
Labels: help wanted

**Comment by Yanunita** [comment] 2021-04-02 09:34
thanks!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
